name: Build First Password Authenticator JAR

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests targeting the main branch
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up JDK 11 (Keycloak 23.0.7 uses Java 11)
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'  # Use Eclipse Temurin (OpenJDK distribution)
          cache: 'maven'  # Cache Maven dependencies for faster builds

      # Step 3: Build the project with Maven
      - name: Build with Maven
        run: mvn clean package -B  # -B for batch mode (non-interactive)

      # Step 4: Upload the JAR as an artifact (optional)
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: first-password-authenticator-jar
          path: target/first-password-authenticator-1.0.0.jar
          retention-days: 7  # Keep the artifact for 7 days