name: Build First Password Authenticator JAR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean package -B

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: keycloak-first-password-authenticator-jar
          path: target/keycloak-first-password-action-1.0.0.jar
          retention-days: 7